@startuml
title ReactJS
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center

frame Virtual_DOM {
  rectangle Componente [
    <b>Componente

    <App />
  ]
}

frame Real_DOM {
  rectangle Elemento [
    <b>Elemento

    <h1>Hello</h1>
  ]
}

Componente -right-> Elemento: render (props, state)

@enduml
