@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true

entity "Investments" as investiments {
  *id : uuid
  name : character
  price: bigint
  origin : character
  category : character
  interest : character
  created_at : timestamp
}
@enduml
