@startuml
title React Native
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center
left to right direction

frame Plataformas {
  rectangle browserDOM [
    <b>Browser DOM

    <p>Hello</p>
  ]
  rectangle iOS [
    <b>iOS

    UITextView
  ]
  rectangle Android [
    <b>Android

    <TextView />
  ]
}

frame Componente {
  rectangle ReactNative [
    <b>React Native

    <Text>Hello</Text>
  ]
}

ReactNative --> browserDOM
ReactNative --> iOS
ReactNative --> Android

@enduml
