@startuml
title POST
hide footbox
skinparam monochrome true

Client -> Server: POST /user/repos
note right: POST /user/repos HTTP/1.1\nHost: https://api.github.com\nAccept: application/vnd.github+json\nAuthorization: Bearer TOKEN\nX-GitHub-Api-Version: 2022-11-28\nContent-Type: application/json\n\n{\n  "name": "github-repo-api",\n  "description": "This is your first repo!",\n  "homepage": "https://github.com",\n  "private": false,\n  "is_template": true\n}
Server -> Client: HTTP/1.1 201 Created
note left: HTTP/1.1 201 Created\nServer: GitHub.com\n\n{\n  "id": 688673759,\n  "node_id": "R_kgDOKQxT3w",\n  "name": "github-repo-api",\n  "full_name": "luizchaves/github-repo-api",\n  ...\n}
@enduml
